### ISSUE TITLE
Datos?

### ISSUE THREAD

**Issue by marcelino-m** [e-gob/transantiago-app#3]
Me encuentro desarrollando un aplicación y necesito obtener  información georeferenciada del transantiago, en particular:
- Base de datos  actualizada de paraderos, y recorridos.

Podrías darme algún hint donde obtener esta información.

Gracias
Marcelo

**Comment by ratollama** [comment]
Yo creo que http://datos.gob.cl/dataset/1587 (sobre todo por que los nombres de las tablas coinciden con los archivos) (no tengo nada que ver con la aplicación)
